// Scripted takes against the sample sites (../sample_sites/WALKTHROUGHS.md).
// Each step is one thing a person does; `note` is what should visibly happen,
// kept so a report can say which part of the script a failure belongs to.
//
//   click  {loc}                 real mouse click
//   type   {loc, text, append?}  click the field, clear (or go to end), type
//   select {loc, option}         choose an option by visible text
//   key    {key}                 press a key on the focused element
//   drag   {loc, to}             press, travel, release
//   wait   {ms}                  a pause a person would take (reading)

const deal = (name) => ({ sel: "article.deal", text: name });

module.exports = {
  "cadence-1.2": {
    site: "/cadence-crm/",
    title: "Advance a deal and watch the forecast move",
    steps: [
      { do: "select", loc: "#owner", option: "Dana Reyes", note: "board narrows to Dana's deals" },
      { do: "click", loc: { ...deal("Camber Logistics"), then: "button.adv" }, note: "Camber moves to Closed Won" },
      { do: "click", loc: { ...deal("Camber Logistics"), then: ".deal-note" }, note: "contact record opens" },
      { do: "click", loc: { sel: "button", text: "Log call", exact: true }, note: "composer focused with prefix" },
      { do: "type", loc: "#noteInput", text: "Confirmed signature date with Ruben.", append: true },
      { do: "click", loc: "#noteBtn", note: "note prepends to the timeline" },
      { do: "click", loc: "#backBtn", note: "back to pipeline, filter kept" },
    ],
  },

  "trackline-2.2": {
    site: "/trackline-issues/",
    title: "Triage the highest-priority issue",
    steps: [
      { do: "click", loc: { sel: "#focusItems button.focus-item" }, note: "the top 'Needs attention' issue opens" },
      { do: "select", loc: "#pAss", option: "Nina Okonkwo", note: "reassigned, toast" },
      { do: "select", loc: "#pPri", option: "Urgent", note: "priority glyph changes" },
      { do: "type", loc: "#cmtInput", text: "Picking this up — repro confirmed on staging." },
      { do: "click", loc: "#cmtBtn", note: "comment appends to the thread" },
      { do: "click", loc: "#subscribeBtn", note: "joins the Subscribed view" },
      { do: "click", loc: "#backBtn", note: "back to the feed; Subscribed count +1" },
    ],
  },

  "helphub-3.2": {
    site: "/helphub-support/",
    title: "Reply to a customer and resolve the ticket",
    steps: [
      { do: "select", loc: "#channelFilter", option: "Email", note: "queue narrows" },
      { do: "click", loc: { sel: 'article.tk[data-id="HH-2417"]' }, note: "thread + context swap in place" },
      { do: "select", loc: "#snippetSel", option: "Confirm resolution", note: "snippet drops into the composer" },
      { do: "type", loc: "#replyInput", text: "I've refunded the duplicate charge of $148.00 — it should clear in 3–5 business days." },
      { do: "click", loc: "#replyBtn", note: "agent bubble appends" },
      { do: "select", loc: "#tStatus", option: "Solved", note: "ticket leaves Open, badge drops" },
      { do: "click", loc: 'button[data-filter="solved"]', note: "HH-2417 is in Solved" },
    ],
  },

  "peoplebase-4.2": {
    site: "/peoplebase-hr/",
    title: "Request time off and watch a balance drop",
    steps: [
      { do: "click", loc: { sel: "article.emp", nth: 0 }, note: "profile opens" },
      { do: "click", loc: "#reqBtn", note: "time-off form opens" },
      { do: "select", loc: "#f-type", option: "Vacation" },
      { do: "date", loc: "#f-from", digits: "05042026", note: "Monday May 4" },
      { do: "date", loc: "#f-to", digits: "05082026", note: "Friday May 8; Days computes 5" },
      { do: "type", loc: "#f-note", text: "Family trip, back on the 11th" },
      { do: "click", loc: "#saveBtn", note: "Pending row appears, vacation balance drops by 5" },
      { do: "click", loc: { sel: "tr", text: "Family trip", then: "button[data-cancel]" }, note: "request cancelled, balance restored" },
    ],
  },

  "cartwright-5.2": {
    site: "/cartwright-commerce/",
    title: "Fulfil a batch of orders at once",
    steps: [
      { do: "click", loc: 'button[data-filter="unfulfilled"]', note: "table narrows to unfulfilled" },
      { do: "click", loc: { sel: "input[data-cb]", nth: 0 }, note: "bulk bar replaces the tabs" },
      { do: "click", loc: { sel: "input[data-cb]", nth: 1 }, note: "select-all goes indeterminate" },
      { do: "click", loc: "#cbAll", note: "every visible order selected" },
      { do: "click", loc: "#bulkFulfil", note: "To fulfill card drops" },
      { do: "click", loc: 'button[data-filter="fulfilled"]', note: "processed orders listed" },
      { do: "click", loc: 'button[data-filter="all"]' },
      { do: "select", loc: "#sortOrders", option: "Highest value", note: "reorders; selection clears" },
    ],
  },

  "mailwing-6.2": {
    site: "/mailwing-campaigns/",
    title: "Edit a draft against the live preview",
    steps: [
      { do: "click", loc: 'button[data-filter="draft"]', note: "drafts only" },
      { do: "click", loc: { sel: "tr.camp", nth: 0 }, note: "builder opens with live preview" },
      { do: "type", loc: "#bHead", text: "Six new pieces, just in time for spring", note: "preview headline mirrors each keystroke" },
      { do: "type", loc: "#bSubject", text: "Six new pieces for the spring table, plus free shipping on every order this week", transient: true, note: "over 60 chars: length warning" },
      { do: "type", loc: "#bSubject", text: "Six new pieces for the spring table", note: "warning clears" },
      { do: "type", loc: "#bPreview", text: "Stoneware, linen and cast iron, picked for the season." },
      { do: "type", loc: "#bCta", text: "Shop the collection" },
      { do: "type", loc: "#bUrl", text: "https://northgate.example/collection" },
      { do: "click", loc: 'button[data-preview="mobile"]', note: "preview narrows to phone width" },
      { do: "click", loc: 'button[data-preview="desktop"]' },
      { do: "click", loc: "#testBtn", note: "standalone preview modal" },
      { do: "click", loc: "#closePreview" },
    ],
  },

  "pulsegraph-7.2": {
    site: "/pulsegraph-analytics/",
    title: "Segment the data by device and source",
    steps: [
      { do: "click", loc: { sel: "article.kpi", text: "Revenue" }, note: "metric follows the tile" },
      { do: "click", loc: { sel: "article.kpi", text: "Sessions" }, note: "back to sessions" },
      { do: "select", loc: "#deviceFilter", option: "Mobile", note: "KPIs, chart and panels change" },
      { do: "click", loc: { sel: "button.rrow", nth: 0 }, note: "source selected" },
      { do: "click", loc: { sel: "button.rrow.active" }, note: "same row again clears it" },
      { do: "click", loc: 'button[data-chart="bar"]', note: "charts switch to bars" },
      { do: "click", loc: 'button[data-chart="line"]' },
    ],
  },

  "lumen-8.2": {
    site: "/lumen-learn-lms/",
    title: "Complete lessons and move the ring",
    steps: [
      { do: "click", loc: 'button.course-link[data-course="CS-140"]', note: "curriculum opens" },
      { do: "click", loc: { sel: "button.lesson-title", text: "Loops" }, note: "study workspace opens" },
      { do: "type", loc: "#lessonNotes", text: "Truthiness is the part I keep forgetting — empty list is False." },
      { do: "click", loc: "#completeLesson", note: "Mark complete & continue: ring, module and weekly goal move" },
      { do: "click", loc: { sel: "button.close[data-close]" }, note: "back to the curriculum" },
      { do: "click", loc: 'button[aria-label="Mark incomplete: Loops"]', note: "untick: weekly count comes back down" },
    ],
  },

  "stratus-9.2": {
    site: "/stratus-console/",
    title: "Recover a degraded resource, then resize it",
    steps: [
      { do: "click", loc: "#actRestart", note: "api-worker-02 back to running" },
      { do: "click", loc: 'a[data-screen="activity"]', note: "restart logged" },
      { do: "type", loc: "#logSearch", text: "api-worker-02" },
      { do: "select", loc: "#logLevel", option: "Error", note: "the historic failure" },
      { do: "click", loc: 'a[data-screen="resources"]' },
      { do: "click", loc: { sel: "button.resource-name", text: "api-worker-02" }, note: "inspector" },
      { do: "click", loc: "#resizeResource", note: "resize dialog" },
      { do: "select", loc: "#resizeSize", option: { last: true }, note: "a larger size" },
      { do: "click", loc: "#applyResize", note: "price updates" },
      { do: "click", loc: "#takeSnapshot", note: "snapshot dialog" },
      { do: "type", loc: "#snapshotLabel", text: "pre-upgrade-worker-02" },
      { do: "click", loc: "#confirmSnapshot" },
      { do: "click", loc: 'a[data-screen="snapshots"]', note: "the new snapshot beside the seeded one" },
    ],
  },

  "ledgerly-10.2": {
    site: "/ledgerly-expenses/",
    title: "Approve one, reject another",
    steps: [
      { do: "select", loc: "#policyFilter", option: "With policy flags", transient: true, note: "four remain" },
      { do: "select", loc: "#policyFilter", option: "No policy flags", note: "only EXP-2146" },
      { do: "click", loc: 'button[data-approve="EXP-2146"]', note: "approved from the queue, no dialog" },
      { do: "click", loc: "#clearFilters", note: "flagged reports come back" },
      { do: "click", loc: { sel: "button.report-link", text: "Dublin prospect meetings" }, note: "EXP-2144 opens" },
      { do: "click", loc: "#decNo", note: "'Return this report' dialog" },
      { do: "click", loc: "#confirmDecision", note: "empty reason refused" },
      { do: "type", loc: "#reviewNote", text: "No receipt for The Dean Hotel, $412.00. Anything over $75 needs one — please attach it and resubmit." },
      { do: "click", loc: "#confirmDecision", note: "Rejected chip and note" },
      { do: "click", loc: 'a[data-screen="queue"]', note: "Awaiting you 3" },
    ],
  },

  // ---------------------------------------------------------------- level 3
  "cadence-1.3": {
    site: "/cadence-crm/",
    title: "Add a deal, then reshape the board around it",
    steps: [
      { do: "click", loc: "#newBtn", note: "modal opens" },
      { do: "type", loc: "#f-co", text: "Sablewood Interiors" },
      { do: "type", loc: "#f-contact", text: "Elena Prosser" },
      { do: "type", loc: "#f-amt", text: "7400" },
      { do: "select", loc: "#f-owner", option: "Priya Venn" },
      { do: "click", loc: "#saveBtn", note: "card at top of Qualifying; totals rise" },
      { do: "select", loc: "#sortOrder", option: "Sort: Highest value" },
      { do: "select", loc: "#stageFilter", option: "Qualifying", transient: true },
      { do: "select", loc: "#stageFilter", option: "All stages" },
      { do: "drag", loc: deal("Sablewood Interiors"), to: 'div.col[data-stage="Proposal"]', note: "moves to Proposal; forecast jumps" },
      { do: "click", loc: 'button[data-view="list"]' },
      { do: "click", loc: 'button[data-view="board"]' },
      { do: "click", loc: { ...deal("Sablewood Interiors"), then: ".deal-note" }, note: "record opens" },
      { do: "click", loc: 'button[data-tab="files"]', note: "deliberate empty state" },
    ],
  },

  "trackline-2.3": {
    site: "/trackline-issues/",
    title: "File a bug, close another, watch the numbers move",
    steps: [
      { do: "click", loc: "#newBtn", note: "composer modal" },
      { do: "type", loc: "#f-title", text: "Gift card balance not applied at checkout" },
      { do: "type", loc: "#f-desc", text: "Reported alongside TRK-241. Balance shows in the cart but the total does not change." },
      { do: "select", loc: "#f-status", option: "Todo" , transient: true },
      { do: "select", loc: "#f-pri", option: "High" },
      { do: "click", loc: "#saveBtn", note: "TRK-250 appears; Open +1" },
      { do: "select", loc: "#sortSel", option: "Newest" },
      { do: "type", loc: "#q", text: "TRK-236" },
      { do: "click", loc: 'article.issue[data-key="TRK-236"]' },
      { do: "select", loc: "#pStatus", option: "Done", note: "toast; group changes" },
      { do: "click", loc: "#backBtn", note: "Done up, In progress down" },
      { do: "click", loc: "#clearFilters" },
      { do: "click", loc: 'button[data-filter="done"]', note: "Completed work — Last 30 days" },
    ],
  },

  "helphub-3.3": {
    site: "/helphub-support/",
    title: "Start from the customer, end with a resolved ticket",
    steps: [
      { do: "click", loc: 'a[data-screen="customers"], [data-screen="customers"]', note: "customers table" },
      { do: "click", loc: 'tr[data-cust="Devon Achebe"]', note: "inbox filtered to Devon, All tab" },
      { do: "click", loc: "#newBtn", note: "new ticket modal" },
      { do: "type", loc: "#f-cust", text: "Devon Achebe" },
      { do: "type", loc: "#f-subj", text: "Upgrade quote for second location" },
      { do: "type", loc: "#f-msg", text: "Following up on the chat — can you send pricing for adding a second gym to the account?" },
      { do: "select", loc: "#f-chan", option: "Email" },
      { do: "click", loc: "#saveBtn", note: "HH-2500 created and selected" },
      { do: "select", loc: "#replyMode", option: "Internal note" },
      { do: "type", loc: "#replyInput", text: "Starter plan — needs Business to add a location. Sending the comparison sheet." },
      { do: "click", loc: "#replyBtn", note: "team-only note bubble" },
      { do: "select", loc: "#replyMode", option: "Reply to customer" },
      { do: "select", loc: "#snippetSel", option: "Share an update" },
      { do: "click", loc: "#replyBtn", note: "agent bubble" },
      { do: "select", loc: "#assignee", option: "Nina Okonkwo" },
      { do: "click", loc: "#solveBtn", note: "resolved; counts refresh" },
      { do: "click", loc: "#clearQueue" },
    ],
  },

  "peoplebase-4.3": {
    site: "/peoplebase-hr/",
    title: "Approve leave, then hire someone",
    steps: [
      { do: "click", loc: "#viewRequests", note: "company-wide queue" },
      { do: "click", loc: { sel: 'button[data-review="Approved"]', nth: 0 }, note: "leaves pending" },
      { do: "click", loc: { sel: 'button[data-review="Declined"]', nth: 0 }, note: "balance returned" },
      { do: "select", loc: "#leaveFilter", option: "All" },
      { do: "click", loc: 'a[data-screen="directory"]', note: "pending total two lower" },
      { do: "click", loc: "#addPerson", note: "form opens" },
      // every required field filled, so the app's own duplicate check runs
      // (with one empty, the browser's native bubble stops the submit first)
      { do: "type", loc: "#e-name", text: "Adaeze Balogun", transient: true },
      { do: "type", loc: "#e-title", text: "Design Lead" },
      { do: "select", loc: "#e-dept", option: "Design" },
      { do: "type", loc: "#e-team", text: "Product Design" },
      { do: "type", loc: "#e-location", text: "Lisbon, Portugal" },
      { do: "type", loc: "#e-email", text: "a.balogun@meridian.example", transient: true },
      { do: "type", loc: "#e-phone", text: "+351 21 555 0139" },
      { do: "select", loc: "#e-manager", option: { index: 1 } },
      { do: "date", loc: "#e-start", digits: "06012026" },
      { do: "click", loc: { sel: "button[type=submit]", text: "Save" }, note: "duplicate rejected inline" },
      { do: "type", loc: "#e-name", text: "Noor Hadid" },
      { do: "type", loc: "#e-email", text: "n.hadid@meridian.example" },
      { do: "click", loc: { sel: "button[type=submit]", text: "Save" }, note: "new card; headcount +1" },
      { do: "type", loc: "#q", text: "Noor" },
      { do: "click", loc: { sel: "article.emp", text: "Noor Hadid" }, note: "20 / 5 / 2 balances" },
    ],
  },

  "cartwright-5.3": {
    site: "/cartwright-commerce/",
    title: "Take an order from creation to shipped",
    steps: [
      { do: "click", loc: "#newBtn", note: "dialog opens" },
      { do: "type", loc: "#f-qty", text: "0", transient: true },
      { do: "type", loc: "#f-price", text: "12.999", transient: true },
      { do: "click", loc: "#saveBtn", note: "both rejected" },
      { do: "type", loc: "#f-cust", text: "Elena Prosser" },
      { do: "type", loc: "#f-item", text: "Cast iron trivet, 8in" },
      { do: "type", loc: "#f-qty", text: "3" },
      { do: "type", loc: "#f-price", text: "34.00" },
      { do: "select", loc: "#f-chan", option: "Online store" },
      { do: "click", loc: "#saveBtn", note: "#1201 at the top" },
      { do: "click", loc: { sel: "tr.ord", text: "#1201" }, note: "detail with itemised totals" },
      { do: "type", loc: "#noteInput", text: "Customer asked for delivery after the 20th." },
      { do: "click", loc: "#noteBtn" },
      { do: "click", loc: "#paymentBtn", note: "payment flips" },
      { do: "click", loc: "#fulfilBtn", note: "fulfillment flips" },
      { do: "click", loc: "#slipBtn", note: "packing slip preview" },
      { do: "click", loc: "#closeSlips" },
      { do: "click", loc: "#backBtn", note: "cards come down" },
    ],
  },

  "mailwing-6.3": {
    site: "/mailwing-campaigns/",
    title: "Duplicate a sent campaign, schedule it, then pull it back",
    steps: [
      { do: "click", loc: 'button[data-filter="sent"]' },
      { do: "click", loc: { sel: "tr.camp", text: "March restock" }, note: "read-only builder" },
      { do: "click", loc: "#duplicateBtn", note: "draft copy" },
      { do: "type", loc: "#bName", text: "April restock announcement" },
      { do: "select", loc: "#bAud", option: "Lapsed 90 days" },
      { do: "type", loc: "#bUrl", text: "northgate.example/collection", transient: true },
      { do: "click", loc: "#sendBtn", note: "rejected: HTTP(S) required" },
      { do: "type", loc: "#bUrl", text: "https://northgate.example/collection" },
      { do: "click", loc: "#sendBtn", note: "review dialog" },
      { do: "click", loc: "#closeReview", note: "back to editor" },
      { do: "click", loc: "#scheduleBtn", note: "schedule dialog" },
      { do: "date", loc: "#scheduleDate", digits: "03102026›0900A", transient: true },
      { do: "click", loc: "#confirmCampaign", note: "rejected: before the Mar 16 reference" },
      { do: "date", loc: "#scheduleDate", digits: "03202026›0900A" },
      { do: "click", loc: "#confirmCampaign", note: "Scheduled; back on the campaign list" },
      { do: "click", loc: 'button[data-filter="scheduled"]' },
      { do: "click", loc: { sel: "tr.camp", text: "April restock announcement" } },
      { do: "click", loc: "#scheduleBtn", note: "Cancel schedule: back to Draft" },
    ],
  },

  "pulsegraph-7.3": {
    site: "/pulsegraph-analytics/",
    title: "Build a saved view and export the series",
    steps: [
      { do: "click", loc: 'button[data-days="7"]' },
      { do: "click", loc: { sel: "article.kpi", text: "Revenue" } },
      { do: "select", loc: "#deviceFilter", option: "Mobile" },
      { do: "click", loc: { sel: "button.rrow", nth: 0 } },
      { do: "click", loc: "#viewReport", note: "drill-down" },
      { do: "click", loc: "#backBtn" },
      { do: "click", loc: "#saveViewBtn", note: "save dialog" },
      { do: "type", loc: "#viewName", text: "Mobile revenue — last 7 days" },
      { do: "click", loc: { sel: "button[type=submit]", text: "Save view" } },
      { do: "click", loc: 'a[data-screen="saved"]', note: "saved views" },
      { do: "click", loc: { sel: "article.saved-card", text: "Email revenue", then: "button[data-open-view]" }, note: "every control jumps" },
      { do: "click", loc: 'a[data-screen="saved"]' },
      { do: "click", loc: { sel: "article.saved-card", text: "Mobile revenue", then: "button[data-open-view]" }, note: "own view restores" },
      { do: "click", loc: "#exportBtn", note: "CSV download" },
    ],
  },

  "lumen-8.3": {
    site: "/lumen-learn-lms/",
    title: "Submit an assignment and work the planner",
    steps: [
      { do: "click", loc: "#goalBtn" },
      { do: "type", loc: "#goalInput", text: "31", transient: true },
      { do: "click", loc: "#saveGoal", note: "rejected: 1–30" },
      { do: "type", loc: "#goalInput", text: "6" },
      { do: "click", loc: "#saveGoal" },
      { do: "click", loc: "#enrollBtn" },
      { do: "type", loc: "#courseTitle", text: "Introduction to Data Ethics" },
      { do: "click", loc: "#saveEnroll", note: "rejected: instructor required" },
      { do: "type", loc: "#instructor", text: "Priya Venn" },
      { do: "select", loc: "#newFormat", option: "Self-paced", transient: true },
      { do: "click", loc: "#saveEnroll" },
      { do: "click", loc: 'button[data-nav="planner"]' },
      { do: "click", loc: { sel: "button[data-assignment]", nth: 0 } },
      { do: "click", loc: "#submitAssignment", note: "rejected: empty" },
      { do: "type", loc: "#assignmentText", text: "Draft critique: the dashboard hides its alert states below the fold. Link to follow." },
      { do: "click", loc: "#saveDraft" },
      { do: "click", loc: "#submitAssignment", note: "receipt" },
      { do: "click", loc: 'button[data-nav="notes"]' },
    ],
  },

  "stratus-9.3": {
    site: "/stratus-console/",
    title: "Provision a resource end to end",
    steps: [
      { do: "click", loc: 'a[data-screen="billing"]', note: "$2,481" },
      { do: "click", loc: 'a[data-screen="resources"]' },
      { do: "click", loc: "#newBtn", note: "wizard step one" },
      { do: "click", loc: 'button.opt[data-type="Compute"]' },
      { do: "select", loc: "#wRegion", option: "eu-west-1" },
      { do: "click", loc: "#wNext" },
      { do: "type", loc: "#wName", text: "API-Worker-05", transient: true },
      { do: "click", loc: "#wNext", note: "rejected: lowercase" },
      { do: "type", loc: "#wName", text: "api-worker-01", transient: true },
      { do: "click", loc: "#wNext", note: "rejected: duplicate" },
      { do: "type", loc: "#wName", text: "api-worker-05" },
      { do: "select", loc: "#wSize", option: { index: 1 } },
      { do: "select", loc: "#wEnv", option: "production", transient: true },
      { do: "click", loc: "#wNext", note: "review" },
      { do: "click", loc: "#wBack" },
      { do: "click", loc: "#wNext" },
      { do: "click", loc: "#wNext", note: "Create resource" },
      { do: "click", loc: "#finishSetup", note: "running" },
      { do: "click", loc: 'a[data-screen="billing"]', note: "total risen" },
      { do: "click", loc: "#editBudget" },
      { do: "type", loc: "#budgetInput", text: "0", transient: true },
      { do: "click", loc: "#saveBudget", note: "rejected" },
      { do: "type", loc: "#budgetInput", text: "2600" },
      { do: "click", loc: "#saveBudget" },
      { do: "click", loc: 'a[data-screen="activity"]' },
    ],
  },

  "ledgerly-10.3": {
    site: "/ledgerly-expenses/",
    title: "Exception approval through to reimbursement",
    steps: [
      { do: "type", loc: "#q", text: "EXP-2148" },
      { do: "click", loc: { sel: "button.report-link", text: "Chicago client visit" } },
      { do: "type", loc: "#decNote", text: "Approved as exception — client dinner pre-cleared by Rowan." },
      { do: "click", loc: "#decOk", note: "exception review dialog" },
      { do: "type", loc: "#reviewNote", text: "", transient: true, note: "clear the pre-filled reason" },
      { do: "click", loc: "#confirmDecision", note: "empty reason rejected" },
      { do: "type", loc: "#reviewNote", text: "Client dinner pre-cleared by Rowan; minibar line stays excluded." },
      { do: "click", loc: "#confirmDecision", note: "approved" },
      { do: "click", loc: "#newBtn" },
      { do: "type", loc: "#f-who", text: "Tomas Okafor" },
      { do: "type", loc: "#f-title", text: "Client visit — Dublin" },
      { do: "type", loc: "#f-merch", text: "Aer Lingus" },
      { do: "type", loc: "#f-amt", text: "412.605", transient: true },
      { do: "click", loc: "#saveBtn", note: "rejected: two decimals" },
      { do: "type", loc: "#f-amt", text: "412.60" },
      { do: "select", loc: "#f-cat", option: "Travel", transient: true },
      { do: "select", loc: "#f-dept", option: "Sales", transient: true },
      { do: "click", loc: "#saveBtn", note: "pending, missing-receipt flag" },
      { do: "click", loc: 'a[data-screen="payments"]' },
      { do: "click", loc: 'button[data-payment="EXP-2148"]' },
      { do: "click", loc: "#confirmPayment", note: "empty reference rejected" },
      { do: "type", loc: "#paymentRef", text: "PAY-0316-2148" },
      { do: "click", loc: "#confirmPayment" },
      { do: "select", loc: "#paymentFilter", option: "Recorded payments" },
      { do: "click", loc: 'a[data-screen="reporting"]' },
    ],
  },
};
